"""initial frontier schema

Revision ID: 92d812626a7d
Revises: 
Create Date: 2026-06-07 16:23:32.274388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d812626a7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_runs',
    sa.Column('crawl_id', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('pages_fetched', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('pages_failed', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('pages_irrelevant', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('bytes_downloaded', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('crawl_id')
    )
    op.create_table('frontier_urls',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('url_hash', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('host', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('relevance_score', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('topic_source', sa.Text(), nullable=True),
    sa.Column('depth', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('discovered_from', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_fetch_after', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash')
    )
    op.create_index('ix_frontier_host', 'frontier_urls', ['host'], unique=False)
    op.create_index(
        'ix_frontier_lease',
        'frontier_urls',
        ['status', 'next_fetch_after', sa.literal_column('priority DESC'), sa.literal_column('relevance_score DESC')],
        unique=False,
    )

    op.create_table('host_state',
    sa.Column('host', sa.Text(), nullable=False),
    sa.Column('is_seed', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('allow', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('robots_txt', sa.Text(), nullable=True),
    sa.Column('robots_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crawl_delay_seconds', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('last_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_allowed_fetch_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('relevant_pages', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('irrelevant_pages', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('host')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('host_state')
    op.drop_index('ix_frontier_lease', table_name='frontier_urls')
    op.drop_index('ix_frontier_host', table_name='frontier_urls')
    op.drop_table('frontier_urls')
    op.drop_table('crawl_runs')
    # ### end Alembic commands ###
